### ISSUE TITLE
set attendee_limit

### ISSUE THREAD

**Issue by mouhsinelonly** [mikemix/wiziq-integration#2]
where can i set maximum attendee_limit

**Comment by mikemix** [comment]
Both immutable builders `Classroom` and `PermaClassroom` use the [Classroom](https://github.com/mikemix/wiziq-integration/blob/master/src/Entity/Traits/ClassroomTrait.php#L65) trait which implements the `withAttendeeLimit` method.

Example usage:

``` php
    $classTitle = 'Webinar title';
    $startTime = new \DateTime('2016-01-31 15:00:00');

    $classroom = Wiziq\Entity\Classroom::build($classTitle, $startTime)
        ->withPresenter(100, 'Adam Smith')
        ->withAttendeeLimit(10);
```

**Comment by mouhsinelonly** [comment]
thank you
