### ISSUE TITLE
use string instead of boolean

### ISSUE THREAD

**Issue by mouhsinelonly** [mikemix/wiziq-integration#4]
when i try to use withCreateRecording(true), the classroom does not get created after i searched i found that wiziq does not accept boolean paramteres but should be as string eg : withCreateRecording("true")

**Comment by mikemix** [comment]
Well, it's good you have mentioned this issue since I also had problems with that method. Are you positive the exact string `true` has to be passed to the server instead of `1` ?

The Wiziq's documentation is very poor and somewhat innacurate, I guess you would agree with me.

**Comment by mouhsinelonly** [comment]
no setting withRecording works Great job
